fastapi/asyncer

mkdocs.yml
pyproject.toml

🔧 Upgrade MkDocs Material and update configs

🔧 Upgrade MkDocs Material and update configs

---

.github/workflows/build-docs.yml
.github/workflows/test.yml

💚 Only run CI on push when on master, to avoid duplicate runs for PRs

💚 Only run CI on push when on master, to avoid duplicate runs for PRs

---

.github/workflows/test.yml

⬆️ Upgrade Codecov GitHub Action

⬆️ Upgrade Codecov GitHub Action

---

.github/workflows/build-docs.yml

👷 Disable installing MkDocs Insiders in forks

👷 Disable installing MkDocs Insiders in forks

---

.github/workflows/build-docs.yml

💚 Fix installing Material for MkDocs Insiders in CI

💚 Fix installing Material for MkDocs Insiders in CI

---

.github/workflows/smokeshow.yml
.github/workflows/test.yml
README.md
docs/index.md
pyproject.toml
scripts/test-cov-html.sh
scripts/test.sh

👷 Move from Codecov to Smokeshow

👷 Move from Codecov to Smokeshow

---

.pre-commit-config.yaml

⬆ Upgrade isort and pre-commit config

⬆ Upgrade isort and pre-commit config

---

docs/help.md

📝 Update help Asyncer docs

---

.github/workflows/build-docs.yml
.github/workflows/publish.yml
.github/workflows/test.yml
pyproject.toml

➖ Deprecate Python 3.6 and upgrade Poetry and Poetry Version Plugin

➖ Deprecate Python 3.6 and upgrade Poetry and Poetry Version Plugin

---

.github/workflows/build-docs.yml
.github/workflows/publish.yml
.github/workflows/test.yml

👷 Add alls-green and tweak CI

---

.github/workflows/build-docs.yml
.github/workflows/test.yml

👷 Update token for Material for MkDocs Insiders

👷 Update token for Material for MkDocs Insiders

---

.github/workflows/build-docs.yml
.github/workflows/deploy-docs.yml

👷 Update docs CI, main branch is main, not master

👷 Update docs CI, main branch is main, not master

---

.github/workflows/deploy-docs.yml

👷 Update docs deploy to Cloudflare pages

👷 Update docs deploy to Cloudflare pages

---

.github/workflows/latest-changes.yml
.github/workflows/publish.yml
.github/workflows/test.yml

👷 Update Debug mode with Tmate for CI

👷 Update Debug mode with Tmate for CI

---

CITATION.cff

🔧 Add `CITATION.cff` file for academic citations

🔧 Add `CITATION.cff` file for academic citations

---

.github/workflows/latest-changes.yml
docs/release-notes.md

👷 Upgrade latest-changes

---

.github/workflows/latest-changes.yml

👷 Update latest changes GitHub Action to use the latest release

👷 Update latest changes GitHub Action to use the latest release

---

.github/workflows/build-docs.yml

👷 Update build docs cache key

---

pyproject.toml

🔧 Update classifiers for Python 3.11 and Python 3.12

🔧 Update classifiers for Python 3.11 and Python 3.12

---

asyncer/__init__.py
pyproject.toml

🔧 Add Ruff config

---

.github/workflows/publish.yml

👷 Update Publish CI Python version to 3.11

👷 Update Publish CI Python version to 3.11

---

.github/workflows/test-redistribute.yml

👷 Tweak CI for test-redistribute, add needed env vars for slim

👷 Tweak CI for test-redistribute, add needed env vars for slim

---

.github/workflows/build-docs.yml
.github/workflows/deploy-docs.yml
.github/workflows/smokeshow.yml
.github/workflows/test.yml

👷 Update GitHub Actions to download and upload artifacts

👷 Update GitHub Actions to download and upload artifacts

---

mkdocs.yml

🔧 Enable auto dark mode

---

data/members.yml
docs/about/index.md
docs/css/custom.css
docs/management-tasks.md
docs/management.md
docs/resources/index.md
docs/tutorial/index.md
mkdocs.yml

📝 Add docs about repo management and team

📝 Add docs about repo management and team

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/privileged.yml
.github/workflows/issue-manager.yml
CITATION.cff
README.md
docs/help.md
docs/index.md
docs/management-tasks.md
mkdocs.yml
pyproject.toml

📝 Change links from github.com/tiangolo/asyncer to github.com/fastapi/asyncer

📝 Change links from github.com/tiangolo/asyncer to github.com/fastapi/asyncer

---

.github/workflows/add-to-project.yml

👷 Update GitHub Action add-to-project

👷 Update GitHub Action add-to-project

---

.github/workflows/labeler.yml

👷 Update GitHub Action labeler permissions and dependencies

👷 Update GitHub Action labeler permissions and dependencies

---

.github/labeler.yml
.github/workflows/labeler.yml

👷 Update GitHub Action labeler to put only one label

👷 Update GitHub Action labeler to put only one label

---

.github/workflows/test.yml
.gitignore
pyproject.toml
scripts/test.sh

🔧 Update converage configs

---

scripts/docs-live.sh
scripts/test-files.sh

🔥 Remove unused scripts

---

.github/workflows/build-docs.yml
.github/workflows/deploy-docs.yml
.github/workflows/smokeshow.yml
.github/workflows/test.yml
requirements-github-actions.txt

👷 Use uv for CI

---

.github/workflows/build-docs.yml

🔧 Update build-docs filter paths

🔧 Update build-docs filter paths
